{
 "title": "my-application",
 "description": "Dashboard for my-application across datacenter and cloud service meshes",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "app",
    "query": {
     "query": "label_values(envoy_cluster_upstream_rq_time_bucket,consul_source_service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Successful Requests (HTTP 200) for Services",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_xx{consul_source_service=\"$app\",envoy_response_code_class=\"2\"}[5m])) by (consul_source_service,consul_source_datacenter) * 300",
     "legendFormat": "{{consul_source_service}}, {{consul_source_datacenter}}"
    }
   ]
  },
  {
   "title": "Errors (HTTP 500) for Services",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_xx{consul_source_service=\"$app\",envoy_response_code_class=\"5\"}[5m])) by (consul_source_service,consul_source_datacenter) * 300",
     "legendFormat": "{{consul_source_service}}, {{consul_source_datacenter}}"
    }
   ]
  },
  {
   "title": "Total active connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(envoy_cluster_upstream_cx_active{consul_source_service=\"$app\"}) by (consul_source_service)",
     "legendFormat": "{{consul_source_service}}"
    }
   ]
  },
  {
   "title": "Downstream Total active connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(envoy_http_downstream_cx_active{consul_source_service=~\"$app\"}) by (consul_source_service)",
     "legendFormat": "{{consul_source_service}}"
    }
   ]
  }
 ]
}