---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: my-application
spec:
  protocol: "http"
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: IngressGateway
metadata:
  name: ingress-gateway
  annotations:
    "consul.hashicorp.com/service-meta-host": "my-application.my-company.net"
    "consul.hashicorp.com/service-meta-weight": "10"
spec:
  listeners:
    - port: 30909
      protocol: http
      services:
        - name: my-application
          hosts:
            - "my-application.my-company.net"
